import { renderLayout } from "@dash/Utils";
import { DndProvider } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";

export const LayoutDragBuilderEdit = ({
    layout,
    dashboardId,
    parentKey,
    debugMode,
    previewMode,
    editMode,
    onClickAdd,
    onClickQuickAdd,
    onDropItem,
    onDragItem,
    onClickRemove,
    onClickShrink,
    onClickExpand,
    onClickEmptyCell,
    onClickContextSettings,
    onSelectWidgetForCell,
    onChangeDirection,
    onChangeOrder,
    onOpenConfig,
    onOpenEvents,
    onSaveConfiguration,
    onProviderSelect = null,
    workspace,
    isDraggable = true,
}) => {
    return isDraggable === true ? (
        <DndProvider backend={HTML5Backend} key={"dnd-provider-edit"}>
            {renderLayout({
                dashboardId,
                layout,
                parentKey,
                debugMode,
                previewMode,
                onClickAdd,
                onClickQuickAdd,
                onClickRemove,
                onClickShrink,
                onClickExpand,
                onClickEmptyCell,
                onClickContextSettings,
                onSelectWidgetForCell,
                onChangeDirection,
                onChangeOrder,
                onOpenConfig,
                onOpenEvents,
                onSaveConfiguration,
                onProviderSelect,
                onDropItem,
                onDragItem,
                workspace,
                editMode,
            })}
        </DndProvider>
    ) : (
        renderLayout({
            dashboardId,
            layout,
            parentKey,
            debugMode,
            previewMode,
            onClickAdd,
            onClickQuickAdd,
            onClickRemove,
            onClickShrink,
            onClickExpand,
            onClickContextSettings,
            onClickEmptyCell,
            onSelectWidgetForCell,
            onChangeDirection,
            onChangeOrder,
            onOpenConfig,
            onOpenEvents,
            onSaveConfiguration,
            onProviderSelect,
            onDropItem,
            onDragItem,
            workspace,
            editMode,
        })
    );
};
