import React, { useEffect, useContext, useState } from "react";
import algoliasearch from "algoliasearch";
import {
    ButtonIcon,
    Panel2,
    Heading,
    SubHeading3,
    InputText,
    AlgoliaSearchBox,
} from "@dash/Common";

import {
    InstantSearch,
    Hits,
} from "react-instantsearch-hooks-web";
import { ThemeContext } from "@dash/Context";
import { Paragraph } from "../../Common";

const apiKey = process.env.REACT_APP_DASH_API_KEY;
const indexName = process.env.REACT_APP_DASH_INDEX_NAME;
const appId = process.env.REACT_APP_DASH_APP_ID;

export const PanelDashboardLoader = ({ onSelecDashboard, onClose }) => {
    const { theme, currentTheme } = useContext(ThemeContext);

    const [, updateState] = React.useState();
    const forceUpdate = React.useCallback(() => updateState({}), []);
    const [searchClient, setSearchClient] = useState(null);

    useEffect(() => {
        initSearchClient();
    });

    function initSearchClient() {
        if (searchClient === null) {
            if (indexName && apiKey && appId) {
                const searchClientTemp = algoliasearch(appId, apiKey);
                setSearchClient(searchClientTemp);
            }
        }
    }

    function Hit({ hit }) {
        return (
            <div
                className="flex flex-col hover:bg-indigo-800 cursor-pointer"
                onClick={() => onSelecDashboard(hit)}
            >
                <div className="flex flex-row rounded bg-gray-900 p-2 px-4">
                    {hit.name}
                </div>
            </div>
        );
    }

    function handleClose() {
        onClose();
    }

    return (
        currentTheme && (
            <Panel2 padding={false} width="w-full" height="h-full">
                <Panel2.Body>
                    <div className="flex flex-row w-full h-full overflow-clip xl:justify-between xl:space-x-4">
                        <div className="flex flex-col rounded p-6 space-y-4 w-1/3">
                            <Heading title={"Load."} padding={false} />
                            <div className="flex-col hidden 2xl:flex w-full space-y-4">
                                <SubHeading3
                                    title={"Pick a dashboard. Any dashboard."}
                                    padding={false}
                                />
                                <Paragraph
                                    padding={false}
                                    textColor={"text-gray-400"}
                                >
                                    Dashboards have been generated by exporting,
                                    and storing the layouts in an Algolia index.
                                    Search the index for Dashboards to load.
                                </Paragraph>
                            </div>
                        </div>
                        <div className="flex flex-col w-2/3 space-y-2">
                            {searchClient !== null && (
                                <InstantSearch
                                    searchClient={searchClient}
                                    indexName={indexName}
                                >
                                    <AlgoliaSearchBox
                                        placeholder={"Search for Dashboards"}
                                    />
                                    <Hits hitComponent={Hit} />
                                </InstantSearch>
                            )}
                        </div>
                    </div>
                </Panel2.Body>
                <Panel2.Footer>
                    <ButtonIcon icon="arrow-left" onClick={handleClose} />
                </Panel2.Footer>
            </Panel2>
        )
    );
};
