import { PanelEditItemHandlers } from "./PanelEditItemHandlers";
import { mock, MockWrapper } from "@dash";

export default {
    title: "PanelEditItemHandlers",
    component: PanelEditItemHandlers,
};

let eventsSelected = null;
let itemTemp = {
    id: 14,
    order: 1,
    scrollable: true,
    component: "SearchMonitorWidget",
    direction: "col",
    hasChildren: 0,
    width: "",
    height: "h-full",
    parent: 13,
    type: "widget",
    workspace: "MonitorWorkspace-workspace",
    listeners: {},
    eventHandlers: ["handleSearchChange"],
    siblingCount: 0,
    componentData: {
        name: "SearchMonitorWidget",
        type: "widget",
        workspace: "MonitorWorkspace-workspace",
        eventHandlers: ["handleSearchChange"],
        id: null,
        userConfig: {},
        styles: {
            backgroundColor: "bg-blue-800",
            borderColor: "border-blue-900",
        },
        componentName: "SearchMonitorWidget",
    },
    uuid: "undefined-SearchMonitorWidget-14",
    userPrefs: {},
    userConfig: {},
    styles: {
        backgroundColor: "bg-blue-800",
        borderColor: "border-blue-900",
    },
    events: [],
    parentWorkspaceName: "layout",
    parentWorkspace: {},
};

let workspaceTemp = {
    id: 1678837021297,
    name: "Sample Dash with search",
    type: {
        id: 1676908596944,
        name: "Demo Folder",
        icon: "seedling",
    },
    label: "New",
    layout: [
        {
            id: 1,
            order: 1,
            scrollable: true,
            component: "Container",
            direction: "row",
            hasChildren: 1,
            canHaveChildren: true,
            width: "w-full",
            height: "h-full",
            parent: 0,
            type: "workspace",
            workspace: "layout",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                canHaveChildren: true,
                userConfig: {},
                workspace: "layout",
                type: "workspace",
                width: "w-full",
            },
            uuid: "undefined-Container-1",
            userPrefs: {},
            userConfig: {},
            styles: {},
            events: [],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
        {
            id: 3,
            order: 2,
            scrollable: false,
            component: "Container",
            direction: "col",
            hasChildren: 1,
            canHaveChildren: true,
            width: "w-3/4 min-w-3/4",
            height: "h-full",
            parent: 1,
            type: "workspace",
            workspace: "layout",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                canHaveChildren: true,
                userConfig: {},
                workspace: "layout",
                type: "workspace",
                width: "w-full",
            },
            uuid: "undefined-Container-3",
            userPrefs: {},
            userConfig: {},
            styles: {},
            events: [],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
        {
            id: 4,
            order: 3,
            scrollable: false,
            component: "Container",
            direction: "col",
            hasChildren: 1,
            canHaveChildren: true,
            width: "w-1/4 min-w-1/4",
            height: "h-full",
            parent: 1,
            type: "workspace",
            workspace: "layout",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                canHaveChildren: true,
                userConfig: {},
                workspace: "layout",
                type: "workspace",
                width: "w-full",
            },
            uuid: "undefined-Container-4",
            userPrefs: {},
            userConfig: {},
            styles: {},
            events: [],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
        {
            id: 5,
            order: 1,
            scrollable: false,
            component: "DemoWorkspace",
            direction: "col",
            hasChildren: 1,
            canHaveChildren: true,
            width: "",
            height: "h-full",
            parent: 16,
            type: "workspace",
            workspace: "DemoWorkspace-workspace",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                name: "DemoWorkspace",
                canHaveChildren: true,
                workspace: "DemoWorkspace-workspace",
                type: "workspace",
                events: [],
                eventHandlers: [],
                styles: {
                    backgroundColor: "bg-blue-900",
                    borderColor: "border-blue-900",
                },
                userConfig: {},
                id: null,
                componentName: "DemoWorkspace",
            },
            uuid: "undefined-DemoWorkspace-5",
            userPrefs: {},
            userConfig: {},
            styles: {
                backgroundColor: "bg-blue-900",
                borderColor: "border-blue-900",
            },
            events: [],
            parentWorkspaceName: "DemoWorkspace-workspace",
            parentWorkspace: {
                id: 5,
                order: 1,
                scrollable: false,
                component: "DemoWorkspace",
                direction: "col",
                hasChildren: 1,
                canHaveChildren: true,
                width: "",
                height: "h-full",
                parent: 16,
                type: "workspace",
                workspace: "DemoWorkspace-workspace",
                listeners: {},
                eventHandlers: [],
                siblingCount: 0,
                componentData: {
                    name: "DemoWorkspace",
                    canHaveChildren: true,
                    workspace: "DemoWorkspace-workspace",
                    type: "workspace",
                    events: [],
                    eventHandlers: [],
                    styles: {
                        backgroundColor: "bg-blue-900",
                        borderColor: "border-blue-900",
                    },
                    userConfig: {},
                    id: null,
                    componentName: "DemoWorkspace",
                },
                uuid: "undefined-DemoWorkspace-5",
                userPrefs: {},
                userConfig: {},
                styles: {
                    backgroundColor: "bg-blue-900",
                    borderColor: "border-blue-900",
                },
                events: [],
            },
        },
        {
            id: 8,
            order: 2,
            scrollable: true,
            component: "DemoWidget",
            direction: "col",
            hasChildren: 0,
            canHaveChildren: false,
            width: "",
            height: "h-full",
            parent: 5,
            type: "widget",
            workspace: "DemoWorkspace-workspace",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                name: "DemoWidget",
                canHaveChildren: false,
                workspace: "DemoWorkspace-workspace",
                type: "widget",
                events: [],
                eventHandlers: [],
                styles: {
                    backgroundColor: "bg-blue-900",
                    borderColor: "border-blue-900",
                },
                userConfig: {
                    title: {
                        type: "text",
                        defaultValue: "Hi.",
                        instructions: "Type in the title for your widget.",
                        options: [],
                        displayName: "Title",
                        required: false,
                    },
                    subtitle: {
                        type: "text",
                        defaultValue: "I am a widget :-)",
                        instructions: "Type in the sub title for your widget.",
                        options: [],
                        displayName: "SubTitle",
                        required: false,
                    },
                },
                id: null,
                componentName: "DemoWidget",
            },
            uuid: "undefined-DemoWidget-8",
            userPrefs: {
                title: "Hi.",
                subtitle: "I am a widget :-)",
            },
            userConfig: {
                title: {
                    type: "text",
                    defaultValue: "Hi.",
                    instructions: "Type in the title for your widget.",
                    options: [],
                    displayName: "Title",
                    required: false,
                },
                subtitle: {
                    type: "text",
                    defaultValue: "I am a widget :-)",
                    instructions: "Type in the sub title for your widget.",
                    options: [],
                    displayName: "SubTitle",
                    required: false,
                },
            },
            styles: {
                backgroundColor: "bg-blue-900",
                borderColor: "border-blue-900",
            },
            events: [],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
        {
            id: 9,
            order: 2,
            scrollable: false,
            component: "AlgoliaSearchWorkspace",
            direction: "col",
            hasChildren: 1,
            canHaveChildren: true,
            width: "",
            height: "h-full",
            parent: 3,
            type: "workspace",
            workspace: "AlgoliaSearchWorkspace-workspace",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                name: "AlgoliaSearchWorkspace",
                type: "workspace",
                canHaveChildren: true,
                workspace: "AlgoliaSearchWorkspace-workspace",
                styles: {
                    backgroundColor: "bg-blue-700",
                    borderColor: "border-blue-800",
                },
                userConfig: {
                    appId: {
                        type: "text",
                        defaultValue: "",
                        instructions: "App Id",
                        options: [],
                        displayName: "App ID",
                        required: true,
                    },
                    apiKey: {
                        type: "secret",
                        defaultValue: "",
                        instructions: "Type in the apiKey",
                        options: [],
                        displayName: "Api Key",
                        required: true,
                    },
                    indexName: {
                        type: "text",
                        defaultValue: "dev_find_accelerator",
                        instructions: "Type in the index name",
                        options: [],
                        displayName: "Index Name",
                        required: true,
                    },
                },
                id: null,
                componentName: "AlgoliaSearchWorkspace",
            },
            uuid: "undefined-AlgoliaSearchWorkspace-9",
            userPrefs: {
                appId: "ZHSCSP4LMX",
                apiKey: "d49594f0fb42dd19944cb46dc49b6639",
                indexName: "dev_find_accelerator",
            },
            userConfig: {
                appId: {
                    type: "text",
                    defaultValue: "",
                    instructions: "App Id",
                    options: [],
                    displayName: "App ID",
                    required: true,
                },
                apiKey: {
                    type: "secret",
                    defaultValue: "",
                    instructions: "Type in the apiKey",
                    options: [],
                    displayName: "Api Key",
                    required: true,
                },
                indexName: {
                    type: "text",
                    defaultValue: "dev_find_accelerator",
                    instructions: "Type in the index name",
                    options: [],
                    displayName: "Index Name",
                    required: true,
                },
            },
            styles: {
                backgroundColor: "bg-blue-700",
                borderColor: "border-blue-800",
            },
            events: [],
            parentWorkspaceName: "AlgoliaSearchWorkspace-workspace",
            parentWorkspace: {
                id: 9,
                order: 2,
                scrollable: false,
                component: "AlgoliaSearchWorkspace",
                direction: "col",
                hasChildren: 1,
                canHaveChildren: true,
                width: "",
                height: "h-full",
                parent: 3,
                type: "workspace",
                workspace: "AlgoliaSearchWorkspace-workspace",
                listeners: {},
                eventHandlers: [],
                siblingCount: 0,
                componentData: {
                    name: "AlgoliaSearchWorkspace",
                    type: "workspace",
                    canHaveChildren: true,
                    workspace: "AlgoliaSearchWorkspace-workspace",
                    styles: {
                        backgroundColor: "bg-blue-700",
                        borderColor: "border-blue-800",
                    },
                    userConfig: {
                        appId: {
                            type: "text",
                            defaultValue: "",
                            instructions: "App Id",
                            options: [],
                            displayName: "App ID",
                            required: true,
                        },
                        apiKey: {
                            type: "secret",
                            defaultValue: "",
                            instructions: "Type in the apiKey",
                            options: [],
                            displayName: "Api Key",
                            required: true,
                        },
                        indexName: {
                            type: "text",
                            defaultValue: "dev_find_accelerator",
                            instructions: "Type in the index name",
                            options: [],
                            displayName: "Index Name",
                            required: true,
                        },
                    },
                    id: null,
                    componentName: "AlgoliaSearchWorkspace",
                },
                uuid: "undefined-AlgoliaSearchWorkspace-9",
                userPrefs: {
                    appId: "ZHSCSP4LMX",
                    apiKey: "d49594f0fb42dd19944cb46dc49b6639",
                    indexName: "dev_find_accelerator",
                },
                userConfig: {
                    appId: {
                        type: "text",
                        defaultValue: "",
                        instructions: "App Id",
                        options: [],
                        displayName: "App ID",
                        required: true,
                    },
                    apiKey: {
                        type: "secret",
                        defaultValue: "",
                        instructions: "Type in the apiKey",
                        options: [],
                        displayName: "Api Key",
                        required: true,
                    },
                    indexName: {
                        type: "text",
                        defaultValue: "dev_find_accelerator",
                        instructions: "Type in the index name",
                        options: [],
                        displayName: "Index Name",
                        required: true,
                    },
                },
                styles: {
                    backgroundColor: "bg-blue-700",
                    borderColor: "border-blue-800",
                },
                events: [],
            },
        },
        {
            id: 10,
            order: 1,
            scrollable: true,
            component: "CustomSearchbar",
            direction: "col",
            hasChildren: 0,
            canHaveChildren: false,
            width: "",
            height: "h-full",
            parent: 9,
            type: "widget",
            workspace: "AlgoliaSearchWorkspace-workspace",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                name: "CustomSearchbar",
                type: "widget",
                workspace: "AlgoliaSearchWorkspace-workspace",
                canHaveChildren: false,
                events: ["searchQueryChanged"],
                id: null,
                userConfig: {},
                styles: {
                    backgroundColor: "bg-blue-800",
                    borderColor: "border-blue-900",
                },
                componentName: "CustomSearchbar",
            },
            uuid: "undefined-CustomSearchbar-10",
            userPrefs: {},
            userConfig: {},
            styles: {
                backgroundColor: "bg-blue-800",
                borderColor: "border-blue-900",
            },
            events: ["searchQueryChanged"],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
        {
            id: 11,
            order: 2,
            scrollable: true,
            component: "CustomRefinements",
            direction: "col",
            hasChildren: 0,
            canHaveChildren: false,
            width: "",
            height: "h-full",
            parent: 9,
            type: "widget",
            workspace: "AlgoliaSearchWorkspace-workspace",
            listeners: {},
            eventHandlers: ["handleSearchChange"],
            siblingCount: 0,
            componentData: {
                name: "CustomRefinements",
                type: "widget",
                workspace: "AlgoliaSearchWorkspace-workspace",
                canHaveChildren: false,
                eventHandlers: ["handleSearchChange"],
                id: null,
                userConfig: {},
                styles: {
                    backgroundColor: "bg-blue-800",
                    borderColor: "border-blue-900",
                },
                componentName: "CustomRefinements",
            },
            uuid: "undefined-CustomRefinements-11",
            userPrefs: {},
            userConfig: {},
            styles: {
                backgroundColor: "bg-blue-800",
                borderColor: "border-blue-900",
            },
            events: [],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
        {
            id: 12,
            order: 3,
            scrollable: true,
            component: "CustomHits",
            direction: "col",
            hasChildren: 0,
            width: "",
            height: "h-full",
            parent: 9,
            type: "widget",
            workspace: "AlgoliaSearchWorkspace-workspace",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                name: "CustomHits",
                type: "widget",
                workspace: "AlgoliaSearchWorkspace-workspace",
                userConfig: {
                    hitComponent: {
                        type: "select",
                        displayName: "Hit Display Component",
                        instructions: "Select the component from the list",
                        options: [
                            {
                                value: "CustomHitFindIndex",
                                displayName: "Custom Hit Find Index",
                            },
                            {
                                value: "CustomHit",
                                displayName: "Custom Hit",
                            },
                        ],
                        required: false,
                    },
                    cols: {
                        type: "select",
                        displayName: "Grid Columns",
                        instructions: "Select the number of columns",
                        options: [
                            {
                                value: 1,
                                displayName: "One",
                            },
                            {
                                value: 2,
                                displayName: "Two",
                            },
                            {
                                value: 3,
                                displayName: "Three",
                            },
                            {
                                value: 4,
                                displayName: "Four",
                            },
                        ],
                        required: false,
                    },
                },
                id: null,
                styles: {
                    backgroundColor: "bg-blue-800",
                    borderColor: "border-blue-900",
                },
                componentName: "CustomHits",
            },
            uuid: "undefined-CustomHits-12",
            userPrefs: {
                hitComponent: "CustomHitFindIndex",
                cols: "3",
            },
            userConfig: {
                hitComponent: {
                    type: "select",
                    displayName: "Hit Display Component",
                    instructions: "Select the component from the list",
                    options: [
                        {
                            value: "CustomHitFindIndex",
                            displayName: "Custom Hit Find Index",
                        },
                        {
                            value: "CustomHit",
                            displayName: "Custom Hit",
                        },
                    ],
                    required: false,
                },
                cols: {
                    type: "select",
                    displayName: "Grid Columns",
                    instructions: "Select the number of columns",
                    options: [
                        {
                            value: 1,
                            displayName: "One",
                        },
                        {
                            value: 2,
                            displayName: "Two",
                        },
                        {
                            value: 3,
                            displayName: "Three",
                        },
                        {
                            value: 4,
                            displayName: "Four",
                        },
                    ],
                    required: false,
                },
            },
            styles: {
                backgroundColor: "bg-blue-800",
                borderColor: "border-blue-900",
            },
            events: [],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
        {
            id: 13,
            order: 2,
            scrollable: false,
            component: "MonitorWorkspace",
            direction: "col",
            hasChildren: 1,
            canHaveChildren: true,
            width: "",
            height: "h-full",
            parent: 17,
            type: "workspace",
            workspace: "MonitorWorkspace-workspace",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                name: "MonitorWorkspace",
                workspace: "MonitorWorkspace-workspace",
                type: "workspace",
                canHaveChildren: true,
                id: null,
                userConfig: {},
                styles: {
                    backgroundColor: "bg-blue-800",
                    borderColor: "border-blue-900",
                },
                componentName: "MonitorWorkspace",
            },
            uuid: "undefined-MonitorWorkspace-13",
            userPrefs: {},
            userConfig: {},
            styles: {
                backgroundColor: "bg-blue-800",
                borderColor: "border-blue-900",
            },
            events: [],
            parentWorkspaceName: "MonitorWorkspace-workspace",
            parentWorkspace: {
                id: 13,
                order: 2,
                scrollable: false,
                component: "MonitorWorkspace",
                direction: "col",
                hasChildren: 1,
                canHaveChildren: true,
                width: "",
                height: "h-full",
                parent: 17,
                type: "workspace",
                workspace: "MonitorWorkspace-workspace",
                listeners: {},
                eventHandlers: [],
                siblingCount: 0,
                componentData: {
                    name: "MonitorWorkspace",
                    workspace: "MonitorWorkspace-workspace",
                    type: "workspace",
                    canHaveChildren: true,
                    id: null,
                    userConfig: {},
                    styles: {
                        backgroundColor: "bg-blue-800",
                        borderColor: "border-blue-900",
                    },
                    componentName: "MonitorWorkspace",
                },
                uuid: "undefined-MonitorWorkspace-13",
                userPrefs: {},
                userConfig: {},
                styles: {
                    backgroundColor: "bg-blue-800",
                    borderColor: "border-blue-900",
                },
                events: [],
            },
        },
        {
            id: 14,
            order: 1,
            scrollable: true,
            component: "SearchMonitorWidget",
            direction: "col",
            hasChildren: 0,
            width: "",
            height: "h-full",
            parent: 13,
            type: "widget",
            workspace: "MonitorWorkspace-workspace",
            listeners: {},
            eventHandlers: ["handleSearchChange"],
            siblingCount: 0,
            componentData: {
                name: "SearchMonitorWidget",
                type: "widget",
                workspace: "MonitorWorkspace-workspace",
                eventHandlers: ["handleSearchChange"],
                id: null,
                userConfig: {},
                styles: {
                    backgroundColor: "bg-blue-800",
                    borderColor: "border-blue-900",
                },
                componentName: "SearchMonitorWidget",
            },
            uuid: "undefined-SearchMonitorWidget-14",
            userPrefs: {},
            userConfig: {},
            styles: {
                backgroundColor: "bg-blue-800",
                borderColor: "border-blue-900",
            },
            events: [],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
        {
            id: 16,
            order: 4,
            scrollable: false,
            component: "Container",
            direction: "col",
            hasChildren: 1,
            canHaveChildren: true,
            width: "w-full",
            height: "h-full",
            parent: 4,
            type: "workspace",
            workspace: "layout",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                canHaveChildren: true,
                userConfig: {},
                workspace: "layout",
                type: "workspace",
                width: "w-full",
            },
            uuid: "undefined-Container-16",
            userPrefs: {},
            userConfig: {},
            styles: {},
            events: [],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
        {
            id: 17,
            order: 3,
            scrollable: false,
            component: "Container",
            direction: "col",
            hasChildren: 1,
            canHaveChildren: true,
            width: "w-full",
            height: "h-full",
            parent: 4,
            type: "workspace",
            workspace: "layout",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                canHaveChildren: true,
                userConfig: {},
                workspace: "layout",
                type: "workspace",
                width: "w-full",
            },
            uuid: "undefined-Container-17",
            userPrefs: {},
            userConfig: {},
            styles: {},
            events: [],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
        {
            id: 18,
            order: 5,
            scrollable: false,
            component: "SaveDataWorkspace",
            direction: "col",
            hasChildren: 1,
            canHaveChildren: true,
            width: "",
            height: "h-full",
            parent: 20,
            type: "workspace",
            workspace: "SaveDataWorkspace-workspace",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                name: "SaveDataWorkspace",
                canHaveChildren: true,
                workspace: "SaveDataWorkspace-workspace",
                type: "workspace",
                events: [],
                eventHandlers: [],
                styles: {
                    backgroundColor: "bg-blue-900",
                    borderColor: "border-blue-900",
                },
                userConfig: {},
                id: null,
                componentName: "SaveDataWorkspace",
            },
            uuid: "undefined-SaveDataWorkspace-18",
            userPrefs: {},
            userConfig: {},
            styles: {
                backgroundColor: "bg-blue-900",
                borderColor: "border-blue-900",
            },
            events: [],
            parentWorkspaceName: "SaveDataWorkspace-workspace",
            parentWorkspace: {
                id: 18,
                order: 5,
                scrollable: false,
                component: "SaveDataWorkspace",
                direction: "col",
                hasChildren: 1,
                canHaveChildren: true,
                width: "",
                height: "h-full",
                parent: 20,
                type: "workspace",
                workspace: "SaveDataWorkspace-workspace",
                listeners: {},
                eventHandlers: [],
                siblingCount: 0,
                componentData: {
                    name: "SaveDataWorkspace",
                    canHaveChildren: true,
                    workspace: "SaveDataWorkspace-workspace",
                    type: "workspace",
                    events: [],
                    eventHandlers: [],
                    styles: {
                        backgroundColor: "bg-blue-900",
                        borderColor: "border-blue-900",
                    },
                    userConfig: {},
                    id: null,
                    componentName: "SaveDataWorkspace",
                },
                uuid: "undefined-SaveDataWorkspace-18",
                userPrefs: {},
                userConfig: {},
                styles: {
                    backgroundColor: "bg-blue-900",
                    borderColor: "border-blue-900",
                },
                events: [],
            },
        },
        {
            id: 19,
            order: 1,
            scrollable: true,
            component: "SaveDataWidget",
            direction: "col",
            hasChildren: 0,
            canHaveChildren: false,
            width: "",
            height: "h-full",
            parent: 18,
            type: "widget",
            workspace: "SaveDataWorkspace-workspace",
            listeners: {},
            eventHandlers: ["handleSearchChange2"],
            siblingCount: 0,
            componentData: {
                name: "SaveDataWidget",
                canHaveChildren: false,
                workspace: "SaveDataWorkspace-workspace",
                type: "widget",
                events: [],
                styles: {
                    backgroundColor: "bg-green-900",
                    borderColor: "border-green-900",
                },
                eventHandlers: ["handleSearchChange2"],
                id: null,
                userConfig: {},
                componentName: "SaveDataWidget",
            },
            uuid: "undefined-SaveDataWidget-19",
            userPrefs: {},
            userConfig: {},
            styles: {
                backgroundColor: "bg-green-900",
                borderColor: "border-green-900",
            },
            events: [],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
        {
            id: 20,
            order: 6,
            scrollable: false,
            component: "Container",
            direction: "col",
            hasChildren: 1,
            canHaveChildren: true,
            width: "w-full",
            height: "h-full",
            parent: 4,
            type: "workspace",
            workspace: "layout",
            listeners: {},
            eventHandlers: [],
            siblingCount: 0,
            componentData: {
                canHaveChildren: true,
                userConfig: {},
                workspace: "layout",
                type: "workspace",
                width: "w-full",
            },
            uuid: "undefined-Container-20",
            userPrefs: {},
            userConfig: {},
            styles: {},
            events: [],
            parentWorkspaceName: "layout",
            parentWorkspace: {},
        },
    ],
};

// function handleUpdate(layoutItem, tempWorkspace) {
//     console.log("handle update ", layoutItem, tempWorkspace);
//     eventsSelected = layoutItem;
//     workspaceTemp = tempWorkspace;
// }

//👇 We create a “template” of how args map to rendering
const Template = (args) => {
    function handleUpdate(layoutItem, tempWorkspace) {
        console.log("handle update ", layoutItem, tempWorkspace);
        eventsSelected = layoutItem;
        workspaceTemp = tempWorkspace;
        itemTemp = layoutItem;
    }

    return (
        <MockWrapper api={mock.api} theme={mock.themes} args={args}>
            <PanelEditItemHandlers
                {...args}
                item={itemTemp}
                workspace={workspaceTemp}
                onUpdate={handleUpdate}
            />
        </MockWrapper>
    );
};

export const Primary = Template.bind({});

Primary.args = {
    open: true,
};
